In [ ]:
import pandas as pd
import numpy as np

def gerar_dataset_completo_nextjs(n_registos=100000):
    dados = []

    for _ in range(n_registos):
        # Escolher o diagnóstico de forma equilibrada (25k para cada)
        diag = np.random.choice([0, 1, 2, 3])

        # 1. Dados Demográficos e Histórico
        idade = np.random.randint(18, 85)
        sexo = np.random.choice([0, 1]) # 0: Masculino, 1: Feminino

        # Fatores de Risco baseados na doença
        if diag == 3:
            fumante = np.random.binomial(1, 0.85)
            convive_fumantes = np.random.binomial(1, 0.60)
            quimicos = np.random.binomial(1, 0.70)
            historico_familiar = np.random.binomial(1, 0.50)
        elif diag == 2:
            fumante = np.random.binomial(1, 0.60)
            convive_fumantes = np.random.binomial(1, 0.50)
            quimicos = np.random.binomial(1, 0.40)
            historico_familiar = np.random.binomial(1, 0.70) # Peso genético alto
        else: # Diag 0 e 1
            fumante = np.random.binomial(1, 0.20)
            convive_fumantes = np.random.binomial(1, 0.30)
            quimicos = np.random.binomial(1, 0.15)
            historico_familiar = np.random.binomial(1, 0.20)

        # 2. Sintomas de Tosse
        if diag == 0:
            tosse = np.random.binomial(1, 0.10)
            tosse_dias = 0 if tosse == 0 else np.random.randint(1, 4)
            tosse_catarro = 0
            tosse_sangue = 0
        elif diag == 1: # Infecção Aguda (Gripe/Bronquite)
            tosse = np.random.binomial(1, 0.95)
            tosse_dias = np.random.randint(2, 10) if tosse == 1 else 0
            tosse_catarro = np.random.binomial(1, 0.70) if tosse == 1 else 0
            tosse_sangue = np.random.binomial(1, 0.02) if tosse == 1 else 0 # Raríssimo
        else: # Diag 2 e 3 (Crónicos)
            tosse = np.random.binomial(1, 0.80)
            tosse_dias = np.random.randint(15, 90) if tosse == 1 else 0 # Tosse crónica
            tosse_catarro = np.random.binomial(1, 0.60) if tosse == 1 else 0
            tosse_sangue = np.random.binomial(1, 0.40) if (diag == 2 and tosse == 1) else 0 # Forte indicador de Classe 2

        # 3. Falta de Ar e Saturação
        if diag == 0:
            dificuldade_respirar = 0
            falta_ar_constante = 0
            nivel_falta_ar = 0 # 0: Nenhuma, 1: Leve, 2: Moderada, 3: Grave
            saturacao = np.random.randint(95, 100)
        elif diag == 1:
            dificuldade_respirar = np.random.binomial(1, 0.40)
            falta_ar_constante = np.random.binomial(1, 0.20)
            nivel_falta_ar = np.random.choice([1, 2], p=[0.7, 0.3]) if dificuldade_respirar == 1 else 0
            saturacao = np.random.randint(93, 98)
        elif diag == 2:
            dificuldade_respirar = np.random.binomial(1, 0.70)
            falta_ar_constante = np.random.binomial(1, 0.60)
            nivel_falta_ar = np.random.choice([1, 2, 3], p=[0.2, 0.5, 0.3]) if dificuldade_respirar == 1 else 0
            saturacao = np.random.randint(88, 95)
        else: # Diag 3 (DPOC / Crise Grave)
            dificuldade_respirar = np.random.binomial(1, 0.95)
            falta_ar_constante = np.random.binomial(1, 0.90)
            nivel_falta_ar = np.random.choice([2, 3], p=[0.3, 0.7]) if dificuldade_respirar == 1 else 0
            saturacao = np.random.randint(80, 92)

        # 4. Outros Sintomas
        if diag == 1: # Agudo
            febre = np.random.binomial(1, 0.85)
            chiado = np.random.binomial(1, 0.50)
            cansaco = np.random.binomial(1, 0.60)
            perda_peso = np.random.binomial(1, 0.05)
            suor_noturno = np.random.binomial(1, 0.10)
            pioram_noite = np.random.binomial(1, 0.40)
        elif diag == 2: # Crónico / Tuberculose / Infecção Profunda
            febre = np.random.binomial(1, 0.50)
            chiado = np.random.binomial(1, 0.40)
            cansaco = np.random.binomial(1, 0.85)
            perda_peso = np.random.binomial(1, 0.80) # Sintoma chave
            suor_noturno = np.random.binomial(1, 0.85) # Sintoma chave
            pioram_noite = np.random.binomial(1, 0.75)
        elif diag == 3: # Obstrutivo / Asma / DPOC
            febre = np.random.binomial(1, 0.10)
            chiado = np.random.binomial(1, 0.90) # Sintoma chave
            cansaco = np.random.binomial(1, 0.80)
            perda_peso = np.random.binomial(1, 0.20)
            suor_noturno = np.random.binomial(1, 0.15)
            pioram_noite = np.random.binomial(1, 0.85) # Sintoma chave
        else: # Saudável (Diag 0)
            febre, chiado, cansaco, perda_peso, suor_noturno, pioram_noite = 0, 0, 0, 0, 0, 0

        dados.append({
            'Fumante': fumante, 'Idade': idade, 'Sexo': sexo, 'Convive_Fumantes': convive_fumantes,
            'Trabalha_Quimicos': quimicos, 'Doencas_Familia': historico_familiar, 'Tosse': tosse,
            'Tosse_Dias': tosse_dias, 'Tosse_Catarro': tosse_catarro, 'Tosse_Sangue': tosse_sangue,
            'Dificuldade_Respirar': dificuldade_respirar, 'Falta_Ar_Constante': falta_ar_constante,
            'Nivel_Falta_Ar': nivel_falta_ar, 'Chiado_Peito': chiado, 'Febre': febre,
            'Cansaco_Frequente': cansaco, 'Perda_Peso_Recente': perda_peso, 'Suor_Noturno': suor_noturno,
            'Pioram_Noite': pioram_noite, 'Saturacao_O2': saturacao,
            'Diagnostico': diag
        })

    return pd.DataFrame(dados)

# Criar o novo arquivo
df_v2 = gerar_dataset_completo_nextjs(100000)
df_v2.to_csv('/content/Dataset_100k_NextJS_Completo.csv.csv', index=False)
print("Novo Dataset Clínico de 100k criado com sucesso!")

Novo Dataset Clínico de 100k criado com sucesso!


In [ ]:
# O erro KeyError ocorreu porque a coluna 'Desempenho' não existe no DataFrame.
# Use uma das colunas existentes, como 'Diagnostico'.
print("Colunas disponíveis:", df_v2.columns.tolist())
print("\nContagem de Diagnósticos:")
print(df_v2['Diagnostico'].value_counts())

Colunas disponíveis: ['Fumante', 'Idade', 'Sexo', 'Convive_Fumantes', 'Trabalha_Quimicos', 'Doencas_Familia', 'Tosse', 'Tosse_Dias', 'Tosse_Catarro', 'Tosse_Sangue', 'Dificuldade_Respirar', 'Falta_Ar_Constante', 'Nivel_Falta_Ar', 'Chiado_Peito', 'Febre', 'Cansaco_Frequente', 'Perda_Peso_Recente', 'Suor_Noturno', 'Pioram_Noite', 'Saturacao_O2', 'Diagnostico']

Contagem de Diagnósticos:
Diagnostico
3    25188
0    25039
1    24903
2    24870
Name: count, dtype: int64


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Carregar o dataset gerado
df = pd.read_csv('/content/Dataset_100k_NextJS_Completo.csv.csv')

# 2. Separar as features (X) e o alvo (y)
X = df.drop('Diagnostico', axis=1)
y = df['Diagnostico']

# 3. Divisão Treino e Teste (80% para treinar, 20% para validar)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Criar e Treinar o Modelo
# Usamos 100 árvores de decisão para garantir que os padrões sejam bem mapeados
modelo = RandomForestClassifier(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

# 5. Avaliação Final
y_pred = modelo.predict(X_test)

print("\n--- Relatório de Classificação ---")
print(classification_report(y_test, y_pred))

print("\n--- Matriz de Confusão ---")
print(confusion_matrix(y_test, y_pred))


--- Relatório de Classificação ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5030
           1       1.00      1.00      1.00      4951
           2       0.97      0.98      0.98      5019
           3       0.98      0.97      0.98      5000

    accuracy                           0.99     20000
   macro avg       0.99      0.99      0.99     20000
weighted avg       0.99      0.99      0.99     20000


--- Matriz de Confusão ---
[[5030    0    0    0]
 [   2 4943    6    0]
 [   0    3 4910  106]
 [   0    0  131 4869]]


In [ ]:
import pandas as pd
import numpy as np

# Substitua pelo nome correto do seu modelo atualizado, caso tenha mudado
# modelo = joblib.load('modelo_diagnostico_v2_completo.pkl')

# Criação de 30 perfis clínicos baseados no novo questionário
# Colunas: Fumante, Idade, Sexo, Convive_Fumantes, Trabalha_Quimicos, Doencas_Familia,
#          Tosse, Tosse_Dias, Tosse_Catarro, Tosse_Sangue, Dificuldade_Respirar,
#          Falta_Ar_Constante, Nivel_Falta_Ar, Chiado_Peito, Febre, Cansaco_Frequente,
#          Perda_Peso_Recente, Suor_Noturno, Pioram_Noite, Saturacao_O2

pacientes_30 = [
    # C0 - Casos Saudáveis / Controles (1 a 7)
    [0, 25, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98], # P1: Jovem saudável
    [0, 40, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 99], # P2: Convive com fumante, sem sintomas
    [1, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97], # P3: Fumante ativo, mas 100% assintomático
    [0, 19, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96], # P4: Histórico familiar, sem sintomas
    [0, 55, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 98], # P5: Trabalha com químicos, assintomático
    [0, 35, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 97], # P6: Tosse leve de 2 dias, sem mais nada
    [0, 62, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96], # P7: Idoso, convive com fumante, estável

    # C1 - Infecções Agudas / Gripe / Bronquite Aguda (8 a 15)
    [0, 28, 1, 0, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 95], # P8: Febre, tosse com catarro há 4 dias
    [1, 45, 0, 0, 0, 0, 1, 7, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 94], # P9: Tosse há uma semana, chiado e febre
    [0, 33, 0, 1, 0, 0, 1, 3, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 96], # P10: Jovem com febre e falta de ar leve aguda
    [0, 50, 1, 0, 0, 1, 1, 6, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 94], # P11: Bronquite aguda típica, muito catarro
    [0, 22, 0, 0, 0, 0, 1, 5, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 93], # P12: Sintomas agudos com falta de ar moderada
    [1, 60, 1, 1, 0, 0, 1, 8, 1, 0, 1, 1, 2, 1, 1, 1, 0, 0, 1, 93], # P13: Idoso com quadro respiratório agudo forte
    [0, 41, 0, 0, 1, 0, 1, 4, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 95], # P14: Trabalhador exposto com gripe forte
    [0, 29, 1, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 96], # P15: Quadro febril com chiado agudo

    # C2 - Condições Crónicas Profundas / Tuberculose / Fibrose (16 a 23)
    [0, 38, 0, 0, 0, 1, 1, 30, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 91], # P16: Tosse com SANGUE há 30 dias, suor noturno e perda de peso
    [1, 52, 1, 1, 0, 0, 1, 45, 0, 1, 1, 1, 3, 1, 0, 1, 1, 1, 1, 89], # P17: Crónico grave com hemoptise e perda de peso
    [0, 47, 0, 0, 1, 1, 1, 60, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 90], # P18: Exposto a químicos, tosse há 2 meses, suor noturno
    [0, 65, 1, 0, 0, 1, 1, 20, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 92], # P19: Idoso, histórico familiar, tosse persistente com sangue
    [0, 30, 0, 0, 0, 0, 1, 40, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 93], # P20: Jovem com quadro crónico clássico (Suor + Perda Peso)
    [1, 58, 0, 1, 0, 1, 1, 50, 1, 0, 1, 1, 3, 1, 1, 1, 1, 1, 1, 88], # P21: Sintomas crónicos severos com saturação baixa
    [0, 42, 1, 0, 1, 0, 1, 25, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 91], # P22: Tosse com sangue e químicos
    [0, 70, 0, 0, 0, 1, 1, 35, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 90], # P23: Idoso com sintomas sistémicos profundos

    # C3 - Doenças Obstrutivas Crónicas / DPOC / Asma Grave (24 a 30)
    [1, 68, 0, 1, 0, 0, 1, 90, 1, 0, 1, 1, 3, 1, 0, 1, 0, 0, 1, 84], # P24: Idoso DPOC típico, fumante pesado, Sat 84 e falta de ar grave
    [1, 55, 1, 0, 1, 1, 1, 60, 1, 0, 1, 1, 3, 1, 0, 1, 0, 0, 1, 82], # P25: Fumante, exposto a químicos, chiado extremo, Sat 82
    [0, 48, 0, 1, 0, 1, 1, 45, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 86], # P26: Crise asmática/obstrutiva severa que piora à noite
    [1, 75, 0, 0, 0, 0, 1, 30, 1, 0, 1, 1, 3, 1, 0, 1, 1, 0, 1, 81], # P27: DPOC avançado, saturação criticamente baixa (81)
    [1, 63, 1, 1, 1, 0, 1, 40, 1, 0, 1, 1, 3, 1, 1, 1, 0, 1, 1, 85], # P28: Fumante pesado com múltiplos agravantes obstrutivos
    [0, 50, 1, 0, 1, 1, 1, 15, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 1, 87], # P29: Obstrutivo puramente ambiental (Químicos + Chiado)
    [1, 72, 0, 1, 0, 1, 1, 60, 1, 0, 1, 1, 3, 1, 0, 1, 0, 0, 1, 83]  # P30: Caso terminal de DPOC, alta dependência de oxigénio
]

colunas_v2 = [
    'Fumante', 'Idade', 'Sexo', 'Convive_Fumantes', 'Trabalha_Quimicos', 'Doencas_Familia',
    'Tosse', 'Tosse_Dias', 'Tosse_Catarro', 'Tosse_Sangue', 'Dificuldade_Respirar',
    'Falta_Ar_Constante', 'Nivel_Falta_Ar', 'Chiado_Peito', 'Febre', 'Cansaco_Frequente',
    'Perda_Peso_Recente', 'Suor_Noturno', 'Pioram_Noite', 'Saturacao_O2'
]

df_teste_30 = pd.DataFrame(pacientes_30, columns=colunas_v2)

# Executar previsões
probabilidades_30 = modelo.predict_proba(df_teste_30)
previsoes_30 = modelo.predict(df_teste_30)

# Exibir os resultados organizados
print("--- ANÁLISE DE PROBABILIDADE: 30 PACIENTES (MODELO V2) ---")
for i, prob in enumerate(probabilidades_30):
    print(f"\nPaciente {i+1:02d}: Predição Final -> Classe {previsoes_30[i]}")
    print(f"Probabilidades: [C0: {prob[0]:.2f}, C1: {prob[1]:.2f}, C2: {prob[2]:.2f}, C3: {prob[3]:.2f}]")

--- ANÁLISE DE PROBABILIDADE: 30 PACIENTES (MODELO V2) ---

Paciente 01: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 02: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 03: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 04: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 05: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 06: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 07: Predição Final -> Classe 0
Probabilidades: [C0: 1.00, C1: 0.00, C2: 0.00, C3: 0.00]

Paciente 08: Predição Final -> Classe 1
Probabilidades: [C0: 0.00, C1: 1.00, C2: 0.00, C3: 0.00]

Paciente 09: Predição Final -> Classe 1
Probabilidades: [C0: 0.00, C1: 1.00, C2: 0.00, C3: 0.00]

Paciente 10: Predição Final -> Classe 1
Probabilidades: [C

In [ ]:
import joblib

# Salvar o modelo e as colunas (importante para manter a ordem)
joblib.dump(modelo, 'modelo_diagnostico_v1.pkl')
joblib.dump(X.columns.tolist(), 'colunas_modelo.pkl')

print("Modelo guardado com sucesso! Já pode usá-lo em novos pacientes.")

Modelo guardado com sucesso! Já pode usá-lo em novos pacientes.
